### ISSUE TITLE
图片显示出现乱码

### ISSUE THREAD

**Issue by MoYoez** [MeetWq/nonebot-plugin-shindan#2]
![Screenshot_2022-03-05-21-15-40-671_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/30306672/156885700-10bdcad6-2a8b-4986-b2a7-2bfa0296c8f8.jpg)

不过应该可以自行修复 这边提醒下作者

**Comment by MeetWq** [comment]
这个感觉是字体的问题，因为是用无头浏览器生成图片的，请确保系统里有中文字体

**Comment by MoYoez** [comment]
> 这个感觉是字体的问题，因为是用无头浏览器生成图片的，请确保系统里有中文字体

okk 谢谢w

不过我建议你写在readme里面

方便别人使用
